name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below to help us understand your request.

  - type: checkboxes
    id: existing-issue
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched existing issues to ensure this feature has not already been requested
          required: true
        - label: I have read the documentation and this feature does not already exist
          required: true

  - type: dropdown
    id: request-type
    attributes:
      label: Request Type
      description: What type of feature request is this?
      options:
        - New Feature (functionality that doesn't exist)
        - Enhancement (improvement to existing functionality)
        - Integration (connect with external service/tool)
        - Performance (speed, efficiency improvements)
        - Accessibility (improve usability for all users)
        - Developer Experience (tooling, APIs, documentation)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: |
        A clear and concise description of what the problem is.
        Example: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: List any alternatives you have considered...
    validations:
      required: false

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Describe the feature from a user's perspective
      placeholder: |
        As a [type of user],
        I want [goal/desire],
        So that [benefit/reason].
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What conditions must be met for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking my work)
        - High (Significantly impacts productivity)
        - Medium (Would be nice to have)
        - Low (Minor convenience)
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Small (Minor change, few files)
        - Medium (Moderate change, multiple files)
        - Large (Significant change, new system/component)
        - Unknown (Not sure)
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Interest
      description: Would you be interested in contributing to this feature?
      options:
        - label: I am willing to submit a pull request for this feature
          required: false
        - label: I am willing to help test this feature
          required: false
        - label: I am willing to help document this feature
          required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, wireframes, or examples from other tools
      placeholder: Drag and drop images here or paste URLs
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the feature request
      placeholder: Add any other context or screenshots about the feature request here...
    validations:
      required: false
